### ISSUE TITLE
No Damage

### ISSUE THREAD

**Issue by WongIong** [WheteThunger/TargetableDrones#2]
The turret doesn't do any damage to the drone
Tried with and without Drone Settings

**Comment by WheteThunger** [comment]
Your server must have a plugin installed which is preventing the drone from taking damage.

**Comment by WongIong** [comment]
but if player shot it, it will still get damaged

**Comment by WongIong** [comment]
it is so weird because the turret does no damage in the first two times' restart
after i restarted the server many times, it works now.
don't know if it will or not working in the next restart.

**Comment by WheteThunger** [comment]
There is no reason that I know of which could cause this. I can only speculate that some plugin is selectively disallowing the drone from taking damage under certain circumstances. For example, maybe you have a plugin that prevents turrets from damaging owned objects (drones are owned by the player who placed them, similar to other deployables).

The procedure for debugging this is the same as for any other issue. Reproduce the issue on your test server, then reduce the number of plugins that are loaded to determine the minimal set of plugins that the issue can be reproduced with. If you can reproduce the issue with only that plugin, then try to determine under which circumstances it can be reproduced. Circumstances include drone owner, turret owner, weapon, attachments, ammunition type, etc. Along the way, share your findings with me in hopes that I can generate new hypotheses for you to test or directions to investigate. If you happen to determine the root cause, please share that so that I can more efficiently help people with similar issues in the future.

**Comment by WongIong** [comment]
So i have checked that if someone with/out permissions who placed the drones, they both won't get damage.

how i "fixed" it:
1. i have all files transferred to other computer for testing it, in this case it caused damage.
2. So then i go back to the main server, restart, and test it again. Nope
3. Then i unloaded all plugins expect this plugin, it works fine. (while the server is running)
4. Place all plugin back to the server. It still works fine. (while the server is running)
5. Restart to test if it is stable enough. YES. After three times reboot it still working.

If i have any information i will update it here.
